name: Emprendia
favicon: null
layout_spectrum: 0.8145336457528174
typography_spectrum: 0.08160359994508326
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2691717373672873
  lightness: 0.06810309714637697
  saturation: 0.9166132425889373
  rhythmicContrast: 0.5099676416721195
purpose: []
